### PR TITLE
Fix validations in add patient

### LINKED ISSUE #115: add-patient: Improve error message
Example command:
`add-patient n/John Doe nric/S1234567D dob/01-01-1912 sex/Male allergy/G6PD allergy/Shellfish e/john@gmail.com p/90010000 a/123 Marina Terrace`

Error message: This patient already exists in clinic book

Tried changing name and it still shows same error message, what is the criteria for unique patient? Not found in User Guide too

Image

### LINKED ISSUE #116: add-patient: Improve phone number validation
Current validation only allow number and minimum is only length 3, should it be allowed for a more flexible validation?

`add-patient n/John Doe nric/S7510505C dob/01-01-1990 sex/MALE allergy/Penicillin allergy/Shellfish e/johnd@example.com p/1234 5678 (HP) 1111-3333 (Office) a/123 Clementi Ave 3, #04-12`

Image

Image

Image

### LINKED ISSUE #117: add-patient: NRIC only allows S or T?
How about foreigner?

Command: `add-patient n/John Doe nric/F0515994Q dob/01-01-1912 sex/Male allergy/G6PD allergy/Shellfish e/john@gmail.com p/90010000 a/123 Marina Terrace`

Error message: "NRICs should start with S or T, followed by 7 digits, and end with a valid checksum letter"

Image

Generated NRIC using
https://samliew.com/nric-generator

### LINKED ISSUE #120: add-patient: Wrong error message for invalid command multiple prefix allergy
`add-patient n/John Doe nric/S7630902G dob/01-01-1990 sex/MALE allergy/Penicillin all/Shellfish e/johnd@example.com p/91234567 a/123 Clementi Ave 3, #04-12`

Similar to #118, but multiple invalid prefix `allergy/Penicillin all/Shellfish` shows a different error message of "Tags names should be alphanumeric", there is no tags in our user guide?

Image

### LINKED ISSUE #149: add-patient: valid email but error says invalid
`add-patient n/John Doe nric/S1234567D dob/01-01-1912 sex/Male allergy/G6PD allergy/Shellfish e/test++a@gmail.com p/90010000 a/123 Marina Terrace`

`test++a@gmail.com` adhere to below

Emails should be of the format local-part@domain and adhere to the following constraints:
1. The local-part should only contain alphanumeric characters and these special characters, excluding the parentheses, (+_.-). The local-part may not start or end with any special characters.
2. This is followed by a '@' and then a domain name. The domain name is made up of domain labels separated by periods.
The domain name must:
    - end with a domain label at least 2 characters long
    - have each domain label start and end with alphanumeric characters
    - have each domain label consist of alphanumeric characters, separated only by hyphens, if any.

Image

### PR DESCRIPTION
**Pull request by veonlok**
Close #115 
Close #117 
Close #116 
Close #120 
Close #149

### CODE REVIEW

File: src/main/java/seedu/clinic/logic/commands/AddPatientCommand.java [hunk 1]
```diff
@@ -42,7 +42,7 @@ public class AddPatientCommand extends AddPersonWithDuplicateWarningCommand<Pati
             + PREFIX_ADDRESS + "123 Marina Terrace ";
 
     public static final String MESSAGE_SUCCESS = "New patient added: %1$s";
-    public static final String MESSAGE_DUPLICATE_PATIENT = "This patient already exists in clinic book";
+    public static final String MESSAGE_DUPLICATE_PATIENT = "This patient's NRIC already exists in clinic book";
```
Comment (teleifo) [inline src/main/java/seedu/clinic/logic/commands/AddPatientCommand.java]: Should this be "NRIC/FIN" instead?

**Review by teleifo — APPROVED** [review]
LGTM

File: src/main/java/seedu/clinic/logic/commands/AddPatientCommand.java (hunk 1 above)
Comment (veonlok) [reply src/main/java/seedu/clinic/logic/commands/AddPatientCommand.java]: yep thanks for bringing this up. updated!
